[package]
name = "derive_contract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "1.0.60", features = ["extra-traits"] }
quote = "1.0.9"

[dev-dependencies]
trybuild = { version = "1.0", features = ["diff"] }

[lib]
proc-macro = true